server:
  port: 8081

spring:
  datasource:
    url: ${ORACLE_URL:jdbc:oracle:thin:@localhost:1521/XEPDB1}
    username: ${ORACLE_USER:ECOCONCE}
    password: ${ORACLE_PASSWORD:ecoconce123}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
    open-in-view: false

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5500}
